//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatmentWarehouseService.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnInfo", Namespace="http://schemas.datacontract.org/2004/07/RDService")]
    [System.SerializableAttribute()]
    public partial class ReturnInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StatmentWarehouseService.ServiceReference.ErrorInfo ErrorInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StatmentWarehouseService.ServiceReference.IDInfo[] IDInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StatmentWarehouseService.ServiceReference.ErrorInfo ErrorInfo {
            get {
                return this.ErrorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorInfoField, value) != true)) {
                    this.ErrorInfoField = value;
                    this.RaisePropertyChanged("ErrorInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StatmentWarehouseService.ServiceReference.IDInfo[] IDInfo {
            get {
                return this.IDInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.IDInfoField, value) != true)) {
                    this.IDInfoField = value;
                    this.RaisePropertyChanged("IDInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/RDService")]
    [System.SerializableAttribute()]
    public partial class ErrorInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorAltTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorAltText {
            get {
                return this.ErrorAltTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorAltTextField, value) != true)) {
                    this.ErrorAltTextField = value;
                    this.RaisePropertyChanged("ErrorAltText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorReference {
            get {
                return this.ErrorReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorReferenceField, value) != true)) {
                    this.ErrorReferenceField = value;
                    this.RaisePropertyChanged("ErrorReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IDInfo", Namespace="http://schemas.datacontract.org/2004/07/RDService")]
    [System.SerializableAttribute()]
    public partial class IDInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDText {
            get {
                return this.IDTextField;
            }
            set {
                if ((object.ReferenceEquals(this.IDTextField, value) != true)) {
                    this.IDTextField = value;
                    this.RaisePropertyChanged("IDText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDType {
            get {
                return this.IDTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IDTypeField, value) != true)) {
                    this.IDTypeField = value;
                    this.RaisePropertyChanged("IDType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDValue {
            get {
                return this.IDValueField;
            }
            set {
                if ((this.IDValueField.Equals(value) != true)) {
                    this.IDValueField = value;
                    this.RaisePropertyChanged("IDValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParams", Namespace="http://schemas.datacontract.org/2004/07/RD")]
    [System.SerializableAttribute()]
    public partial class QueryParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StatmentWarehouseService.ServiceReference.Pair[] PARAMSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARAM_ORDERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARAM_SELECTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARAM_TARGETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARAM_WHEREField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StatmentWarehouseService.ServiceReference.Pair[] PARAMS {
            get {
                return this.PARAMSField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAMSField, value) != true)) {
                    this.PARAMSField = value;
                    this.RaisePropertyChanged("PARAMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARAM_ORDER {
            get {
                return this.PARAM_ORDERField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAM_ORDERField, value) != true)) {
                    this.PARAM_ORDERField = value;
                    this.RaisePropertyChanged("PARAM_ORDER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARAM_SELECT {
            get {
                return this.PARAM_SELECTField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAM_SELECTField, value) != true)) {
                    this.PARAM_SELECTField = value;
                    this.RaisePropertyChanged("PARAM_SELECT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARAM_TARGET {
            get {
                return this.PARAM_TARGETField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAM_TARGETField, value) != true)) {
                    this.PARAM_TARGETField = value;
                    this.RaisePropertyChanged("PARAM_TARGET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARAM_WHERE {
            get {
                return this.PARAM_WHEREField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAM_WHEREField, value) != true)) {
                    this.PARAM_WHEREField = value;
                    this.RaisePropertyChanged("PARAM_WHERE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pair", Namespace="http://schemas.datacontract.org/2004/07/RD")]
    [System.SerializableAttribute()]
    public partial class Pair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALUEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALUE {
            get {
                return this.VALUEField;
            }
            set {
                if ((object.ReferenceEquals(this.VALUEField, value) != true)) {
                    this.VALUEField = value;
                    this.RaisePropertyChanged("VALUE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuditReference", Namespace="http://schemas.datacontract.org/2004/07/RD")]
    [System.SerializableAttribute()]
    public partial class AuditReference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuditRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BillAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BillCenterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillChargeDescrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BillVATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StatmentWarehouseService.ServiceReference.AuditDocument[] DocumentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionType {
            get {
                return this.ActionTypeField;
            }
            set {
                if ((this.ActionTypeField.Equals(value) != true)) {
                    this.ActionTypeField = value;
                    this.RaisePropertyChanged("ActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuditRef {
            get {
                return this.AuditRefField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditRefField, value) != true)) {
                    this.AuditRefField = value;
                    this.RaisePropertyChanged("AuditRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BillAmount {
            get {
                return this.BillAmountField;
            }
            set {
                if ((this.BillAmountField.Equals(value) != true)) {
                    this.BillAmountField = value;
                    this.RaisePropertyChanged("BillAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BillCenterID {
            get {
                return this.BillCenterIDField;
            }
            set {
                if ((this.BillCenterIDField.Equals(value) != true)) {
                    this.BillCenterIDField = value;
                    this.RaisePropertyChanged("BillCenterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillChargeDescr {
            get {
                return this.BillChargeDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.BillChargeDescrField, value) != true)) {
                    this.BillChargeDescrField = value;
                    this.RaisePropertyChanged("BillChargeDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BillVAT {
            get {
                return this.BillVATField;
            }
            set {
                if ((this.BillVATField.Equals(value) != true)) {
                    this.BillVATField = value;
                    this.RaisePropertyChanged("BillVAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StatmentWarehouseService.ServiceReference.AuditDocument[] Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuditDocument", Namespace="http://schemas.datacontract.org/2004/07/RD")]
    [System.SerializableAttribute()]
    public partial class AuditDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocAttachementFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocAttachementFilenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DocDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocReferenceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocRemarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocAttachementFile {
            get {
                return this.DocAttachementFileField;
            }
            set {
                if ((object.ReferenceEquals(this.DocAttachementFileField, value) != true)) {
                    this.DocAttachementFileField = value;
                    this.RaisePropertyChanged("DocAttachementFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocAttachementFilename {
            get {
                return this.DocAttachementFilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocAttachementFilenameField, value) != true)) {
                    this.DocAttachementFilenameField = value;
                    this.RaisePropertyChanged("DocAttachementFilename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DocDate {
            get {
                return this.DocDateField;
            }
            set {
                if ((this.DocDateField.Equals(value) != true)) {
                    this.DocDateField = value;
                    this.RaisePropertyChanged("DocDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocReference {
            get {
                return this.DocReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.DocReferenceField, value) != true)) {
                    this.DocReferenceField = value;
                    this.RaisePropertyChanged("DocReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocReferenceType {
            get {
                return this.DocReferenceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocReferenceTypeField, value) != true)) {
                    this.DocReferenceTypeField = value;
                    this.RaisePropertyChanged("DocReferenceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocRemarks {
            get {
                return this.DocRemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.DocRemarksField, value) != true)) {
                    this.DocRemarksField = value;
                    this.RaisePropertyChanged("DocRemarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", ConfigurationName="ServiceReference.IRDService")]
    public interface IRDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/Version", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/VersionResponse")]
        string Version(int atype);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/Version", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/VersionResponse")]
        System.Threading.Tasks.Task<string> VersionAsync(int atype);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/GetOperationSchema", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/GetOperationSchemaResponse")]
        string GetOperationSchema(string operationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/GetOperationSchema", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/GetOperationSchemaResponse")]
        System.Threading.Tasks.Task<string> GetOperationSchemaAsync(string operationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/WebLogin", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/WebLoginResponse")]
        StatmentWarehouseService.ServiceReference.WebLoginResponse WebLogin(StatmentWarehouseService.ServiceReference.WebLoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/WebLogin", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/WebLoginResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.WebLoginResponse> WebLoginAsync(StatmentWarehouseService.ServiceReference.WebLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/RegardLogin", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/RegardLoginResponse")]
        StatmentWarehouseService.ServiceReference.RegardLoginResponse RegardLogin(StatmentWarehouseService.ServiceReference.RegardLoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/RegardLogin", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/RegardLoginResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.RegardLoginResponse> RegardLoginAsync(StatmentWarehouseService.ServiceReference.RegardLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DependLogin", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DependLoginResponse")]
        StatmentWarehouseService.ServiceReference.DependLoginResponse DependLogin(StatmentWarehouseService.ServiceReference.DependLoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DependLogin", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DependLoginResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DependLoginResponse> DependLoginAsync(StatmentWarehouseService.ServiceReference.DependLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/Logout", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/LogoutResponse")]
        StatmentWarehouseService.ServiceReference.ReturnInfo Logout(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/Logout", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/LogoutResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.ReturnInfo> LogoutAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/LoginChangeWorkgroup", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/LoginChangeWorkgroupResponse")]
        StatmentWarehouseService.ServiceReference.ReturnInfo LoginChangeWorkgroup(string sessionId, int workgroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/LoginChangeWorkgroup", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/LoginChangeWorkgroupResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.ReturnInfo> LoginChangeWorkgroupAsync(string sessionId, int workgroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetListZIP", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetListZIPResponse")]
        StatmentWarehouseService.ServiceReference.DataSetListZIPResponse DataSetListZIP(StatmentWarehouseService.ServiceReference.DataSetListZIPRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetListZIP", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetListZIPResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DataSetListZIPResponse> DataSetListZIPAsync(StatmentWarehouseService.ServiceReference.DataSetListZIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetList", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetListResponse")]
        StatmentWarehouseService.ServiceReference.DataSetListResponse DataSetList(StatmentWarehouseService.ServiceReference.DataSetListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetList", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetListResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DataSetListResponse> DataSetListAsync(StatmentWarehouseService.ServiceReference.DataSetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetUpdate", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetUpdateResponse")]
        StatmentWarehouseService.ServiceReference.DataSetUpdateResponse DataSetUpdate(StatmentWarehouseService.ServiceReference.DataSetUpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetUpdate", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetUpdateResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DataSetUpdateResponse> DataSetUpdateAsync(StatmentWarehouseService.ServiceReference.DataSetUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetUpdateZIP", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetUpdateZIPResponse")]
        StatmentWarehouseService.ServiceReference.DataSetUpdateZIPResponse DataSetUpdateZIP(StatmentWarehouseService.ServiceReference.DataSetUpdateZIPRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetUpdateZIP", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetUpdateZIPResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DataSetUpdateZIPResponse> DataSetUpdateZIPAsync(StatmentWarehouseService.ServiceReference.DataSetUpdateZIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetConfirm", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetConfirmResponse")]
        StatmentWarehouseService.ServiceReference.ReturnInfo DataSetConfirm(int auditId, string sessionId, string auditReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetConfirm", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetConfirmResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.ReturnInfo> DataSetConfirmAsync(int auditId, string sessionId, string auditReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetReject", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetRejectResponse")]
        StatmentWarehouseService.ServiceReference.ReturnInfo DataSetReject(int auditId, string sessionId, string auditReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetReject", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DataSetRejectResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.ReturnInfo> DataSetRejectAsync(int auditId, string sessionId, string auditReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/GetOptions", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/GetOptionsResponse")]
        StatmentWarehouseService.ServiceReference.QueryParams[] GetOptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/GetOptions", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/GetOptionsResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.QueryParams[]> GetOptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DefineAuditReference", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DefineAuditReferenceResponse")]
        StatmentWarehouseService.ServiceReference.AuditReference DefineAuditReference();
        
        [System.ServiceModel.OperationContractAttribute(Action="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DefineAuditReference", ReplyAction="HTTP://WWW.PERCIVAL.CO.UK/ML7/IRDService/DefineAuditReferenceResponse")]
        System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.AuditReference> DefineAuditReferenceAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WebLogin", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class WebLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public string clientVersion;
        
        public WebLoginRequest() {
        }
        
        public WebLoginRequest(string user, string password, string clientVersion) {
            this.user = user;
            this.password = password;
            this.clientVersion = clientVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WebLoginResponse", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class WebLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public StatmentWarehouseService.ServiceReference.ReturnInfo WebLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string sessionId;
        
        public WebLoginResponse() {
        }
        
        public WebLoginResponse(StatmentWarehouseService.ServiceReference.ReturnInfo WebLoginResult, string sessionId) {
            this.WebLoginResult = WebLoginResult;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegardLogin", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class RegardLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public string clientVersion;
        
        public RegardLoginRequest() {
        }
        
        public RegardLoginRequest(string user, string password, string clientVersion) {
            this.user = user;
            this.password = password;
            this.clientVersion = clientVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegardLoginResponse", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class RegardLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public StatmentWarehouseService.ServiceReference.ReturnInfo RegardLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string sessionId;
        
        public RegardLoginResponse() {
        }
        
        public RegardLoginResponse(StatmentWarehouseService.ServiceReference.ReturnInfo RegardLoginResult, string sessionId) {
            this.RegardLoginResult = RegardLoginResult;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DependLogin", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DependLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public string clientVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=3)]
        public string participant;
        
        public DependLoginRequest() {
        }
        
        public DependLoginRequest(string user, string password, string clientVersion, string participant) {
            this.user = user;
            this.password = password;
            this.clientVersion = clientVersion;
            this.participant = participant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DependLoginResponse", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DependLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public StatmentWarehouseService.ServiceReference.ReturnInfo DependLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string sessionId;
        
        public DependLoginResponse() {
        }
        
        public DependLoginResponse(StatmentWarehouseService.ServiceReference.ReturnInfo DependLoginResult, string sessionId) {
            this.DependLoginResult = DependLoginResult;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetListZIP", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DataSetListZIPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public int top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=3)]
        public string where;
        
        public DataSetListZIPRequest() {
        }
        
        public DataSetListZIPRequest(string sessionId, string name, int top, string where) {
            this.sessionId = sessionId;
            this.name = name;
            this.top = top;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetListZIPResponse", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DataSetListZIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetListZIPResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string schema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public byte[] data;
        
        public DataSetListZIPResponse() {
        }
        
        public DataSetListZIPResponse(StatmentWarehouseService.ServiceReference.ReturnInfo DataSetListZIPResult, string schema, byte[] data) {
            this.DataSetListZIPResult = DataSetListZIPResult;
            this.schema = schema;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetList", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DataSetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public int top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=3)]
        public string where;
        
        public DataSetListRequest() {
        }
        
        public DataSetListRequest(string sessionId, string name, int top, string where) {
            this.sessionId = sessionId;
            this.name = name;
            this.top = top;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetListResponse", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DataSetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string schema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public string data;
        
        public DataSetListResponse() {
        }
        
        public DataSetListResponse(StatmentWarehouseService.ServiceReference.ReturnInfo DataSetListResult, string schema, string data) {
            this.DataSetListResult = DataSetListResult;
            this.schema = schema;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetUpdate", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DataSetUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public int auditId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=3)]
        public int batchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=4)]
        public string data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=5)]
        public string auditReference;
        
        public DataSetUpdateRequest() {
        }
        
        public DataSetUpdateRequest(int auditId, string sessionId, string name, int batchId, string data, string auditReference) {
            this.auditId = auditId;
            this.sessionId = sessionId;
            this.name = name;
            this.batchId = batchId;
            this.data = data;
            this.auditReference = auditReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetUpdateResponse", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DataSetUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetUpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public int auditId;
        
        public DataSetUpdateResponse() {
        }
        
        public DataSetUpdateResponse(StatmentWarehouseService.ServiceReference.ReturnInfo DataSetUpdateResult, int auditId) {
            this.DataSetUpdateResult = DataSetUpdateResult;
            this.auditId = auditId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetUpdateZIP", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DataSetUpdateZIPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public int auditId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=2)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=3)]
        public int batchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=4)]
        public byte[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=5)]
        public string auditReference;
        
        public DataSetUpdateZIPRequest() {
        }
        
        public DataSetUpdateZIPRequest(int auditId, string sessionId, string name, int batchId, byte[] data, string auditReference) {
            this.auditId = auditId;
            this.sessionId = sessionId;
            this.name = name;
            this.batchId = batchId;
            this.data = data;
            this.auditReference = auditReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetUpdateZIPResponse", WrapperNamespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", IsWrapped=true)]
    public partial class DataSetUpdateZIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=0)]
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetUpdateZIPResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HTTP://WWW.PERCIVAL.CO.UK/ML7", Order=1)]
        public int auditId;
        
        public DataSetUpdateZIPResponse() {
        }
        
        public DataSetUpdateZIPResponse(StatmentWarehouseService.ServiceReference.ReturnInfo DataSetUpdateZIPResult, int auditId) {
            this.DataSetUpdateZIPResult = DataSetUpdateZIPResult;
            this.auditId = auditId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRDServiceChannel : StatmentWarehouseService.ServiceReference.IRDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RDServiceClient : System.ServiceModel.ClientBase<StatmentWarehouseService.ServiceReference.IRDService>, StatmentWarehouseService.ServiceReference.IRDService {
        
        public RDServiceClient() {
        }
        
        public RDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Version(int atype) {
            return base.Channel.Version(atype);
        }
        
        public System.Threading.Tasks.Task<string> VersionAsync(int atype) {
            return base.Channel.VersionAsync(atype);
        }
        
        public string GetOperationSchema(string operationName) {
            return base.Channel.GetOperationSchema(operationName);
        }
        
        public System.Threading.Tasks.Task<string> GetOperationSchemaAsync(string operationName) {
            return base.Channel.GetOperationSchemaAsync(operationName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatmentWarehouseService.ServiceReference.WebLoginResponse StatmentWarehouseService.ServiceReference.IRDService.WebLogin(StatmentWarehouseService.ServiceReference.WebLoginRequest request) {
            return base.Channel.WebLogin(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo WebLogin(string user, string password, string clientVersion, out string sessionId) {
            StatmentWarehouseService.ServiceReference.WebLoginRequest inValue = new StatmentWarehouseService.ServiceReference.WebLoginRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.clientVersion = clientVersion;
            StatmentWarehouseService.ServiceReference.WebLoginResponse retVal = ((StatmentWarehouseService.ServiceReference.IRDService)(this)).WebLogin(inValue);
            sessionId = retVal.sessionId;
            return retVal.WebLoginResult;
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.WebLoginResponse> WebLoginAsync(StatmentWarehouseService.ServiceReference.WebLoginRequest request) {
            return base.Channel.WebLoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatmentWarehouseService.ServiceReference.RegardLoginResponse StatmentWarehouseService.ServiceReference.IRDService.RegardLogin(StatmentWarehouseService.ServiceReference.RegardLoginRequest request) {
            return base.Channel.RegardLogin(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo RegardLogin(string user, string password, string clientVersion, out string sessionId) {
            StatmentWarehouseService.ServiceReference.RegardLoginRequest inValue = new StatmentWarehouseService.ServiceReference.RegardLoginRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.clientVersion = clientVersion;
            StatmentWarehouseService.ServiceReference.RegardLoginResponse retVal = ((StatmentWarehouseService.ServiceReference.IRDService)(this)).RegardLogin(inValue);
            sessionId = retVal.sessionId;
            return retVal.RegardLoginResult;
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.RegardLoginResponse> RegardLoginAsync(StatmentWarehouseService.ServiceReference.RegardLoginRequest request) {
            return base.Channel.RegardLoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatmentWarehouseService.ServiceReference.DependLoginResponse StatmentWarehouseService.ServiceReference.IRDService.DependLogin(StatmentWarehouseService.ServiceReference.DependLoginRequest request) {
            return base.Channel.DependLogin(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo DependLogin(string user, string password, string clientVersion, string participant, out string sessionId) {
            StatmentWarehouseService.ServiceReference.DependLoginRequest inValue = new StatmentWarehouseService.ServiceReference.DependLoginRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.clientVersion = clientVersion;
            inValue.participant = participant;
            StatmentWarehouseService.ServiceReference.DependLoginResponse retVal = ((StatmentWarehouseService.ServiceReference.IRDService)(this)).DependLogin(inValue);
            sessionId = retVal.sessionId;
            return retVal.DependLoginResult;
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DependLoginResponse> DependLoginAsync(StatmentWarehouseService.ServiceReference.DependLoginRequest request) {
            return base.Channel.DependLoginAsync(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo Logout(string sessionId) {
            return base.Channel.Logout(sessionId);
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.ReturnInfo> LogoutAsync(string sessionId) {
            return base.Channel.LogoutAsync(sessionId);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo LoginChangeWorkgroup(string sessionId, int workgroupId) {
            return base.Channel.LoginChangeWorkgroup(sessionId, workgroupId);
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.ReturnInfo> LoginChangeWorkgroupAsync(string sessionId, int workgroupId) {
            return base.Channel.LoginChangeWorkgroupAsync(sessionId, workgroupId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatmentWarehouseService.ServiceReference.DataSetListZIPResponse StatmentWarehouseService.ServiceReference.IRDService.DataSetListZIP(StatmentWarehouseService.ServiceReference.DataSetListZIPRequest request) {
            return base.Channel.DataSetListZIP(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetListZIP(string sessionId, string name, int top, string where, out string schema, out byte[] data) {
            StatmentWarehouseService.ServiceReference.DataSetListZIPRequest inValue = new StatmentWarehouseService.ServiceReference.DataSetListZIPRequest();
            inValue.sessionId = sessionId;
            inValue.name = name;
            inValue.top = top;
            inValue.where = where;
            StatmentWarehouseService.ServiceReference.DataSetListZIPResponse retVal = ((StatmentWarehouseService.ServiceReference.IRDService)(this)).DataSetListZIP(inValue);
            schema = retVal.schema;
            data = retVal.data;
            return retVal.DataSetListZIPResult;
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DataSetListZIPResponse> DataSetListZIPAsync(StatmentWarehouseService.ServiceReference.DataSetListZIPRequest request) {
            return base.Channel.DataSetListZIPAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatmentWarehouseService.ServiceReference.DataSetListResponse StatmentWarehouseService.ServiceReference.IRDService.DataSetList(StatmentWarehouseService.ServiceReference.DataSetListRequest request) {
            return base.Channel.DataSetList(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetList(string sessionId, string name, int top, string where, out string schema, out string data) {
            StatmentWarehouseService.ServiceReference.DataSetListRequest inValue = new StatmentWarehouseService.ServiceReference.DataSetListRequest();
            inValue.sessionId = sessionId;
            inValue.name = name;
            inValue.top = top;
            inValue.where = where;
            StatmentWarehouseService.ServiceReference.DataSetListResponse retVal = ((StatmentWarehouseService.ServiceReference.IRDService)(this)).DataSetList(inValue);
            schema = retVal.schema;
            data = retVal.data;
            return retVal.DataSetListResult;
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DataSetListResponse> DataSetListAsync(StatmentWarehouseService.ServiceReference.DataSetListRequest request) {
            return base.Channel.DataSetListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatmentWarehouseService.ServiceReference.DataSetUpdateResponse StatmentWarehouseService.ServiceReference.IRDService.DataSetUpdate(StatmentWarehouseService.ServiceReference.DataSetUpdateRequest request) {
            return base.Channel.DataSetUpdate(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetUpdate(ref int auditId, string sessionId, string name, int batchId, string data, string auditReference) {
            StatmentWarehouseService.ServiceReference.DataSetUpdateRequest inValue = new StatmentWarehouseService.ServiceReference.DataSetUpdateRequest();
            inValue.auditId = auditId;
            inValue.sessionId = sessionId;
            inValue.name = name;
            inValue.batchId = batchId;
            inValue.data = data;
            inValue.auditReference = auditReference;
            StatmentWarehouseService.ServiceReference.DataSetUpdateResponse retVal = ((StatmentWarehouseService.ServiceReference.IRDService)(this)).DataSetUpdate(inValue);
            auditId = retVal.auditId;
            return retVal.DataSetUpdateResult;
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DataSetUpdateResponse> DataSetUpdateAsync(StatmentWarehouseService.ServiceReference.DataSetUpdateRequest request) {
            return base.Channel.DataSetUpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatmentWarehouseService.ServiceReference.DataSetUpdateZIPResponse StatmentWarehouseService.ServiceReference.IRDService.DataSetUpdateZIP(StatmentWarehouseService.ServiceReference.DataSetUpdateZIPRequest request) {
            return base.Channel.DataSetUpdateZIP(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetUpdateZIP(ref int auditId, string sessionId, string name, int batchId, byte[] data, string auditReference) {
            StatmentWarehouseService.ServiceReference.DataSetUpdateZIPRequest inValue = new StatmentWarehouseService.ServiceReference.DataSetUpdateZIPRequest();
            inValue.auditId = auditId;
            inValue.sessionId = sessionId;
            inValue.name = name;
            inValue.batchId = batchId;
            inValue.data = data;
            inValue.auditReference = auditReference;
            StatmentWarehouseService.ServiceReference.DataSetUpdateZIPResponse retVal = ((StatmentWarehouseService.ServiceReference.IRDService)(this)).DataSetUpdateZIP(inValue);
            auditId = retVal.auditId;
            return retVal.DataSetUpdateZIPResult;
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.DataSetUpdateZIPResponse> DataSetUpdateZIPAsync(StatmentWarehouseService.ServiceReference.DataSetUpdateZIPRequest request) {
            return base.Channel.DataSetUpdateZIPAsync(request);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetConfirm(int auditId, string sessionId, string auditReference) {
            return base.Channel.DataSetConfirm(auditId, sessionId, auditReference);
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.ReturnInfo> DataSetConfirmAsync(int auditId, string sessionId, string auditReference) {
            return base.Channel.DataSetConfirmAsync(auditId, sessionId, auditReference);
        }
        
        public StatmentWarehouseService.ServiceReference.ReturnInfo DataSetReject(int auditId, string sessionId, string auditReference) {
            return base.Channel.DataSetReject(auditId, sessionId, auditReference);
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.ReturnInfo> DataSetRejectAsync(int auditId, string sessionId, string auditReference) {
            return base.Channel.DataSetRejectAsync(auditId, sessionId, auditReference);
        }
        
        public StatmentWarehouseService.ServiceReference.QueryParams[] GetOptions() {
            return base.Channel.GetOptions();
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.QueryParams[]> GetOptionsAsync() {
            return base.Channel.GetOptionsAsync();
        }
        
        public StatmentWarehouseService.ServiceReference.AuditReference DefineAuditReference() {
            return base.Channel.DefineAuditReference();
        }
        
        public System.Threading.Tasks.Task<StatmentWarehouseService.ServiceReference.AuditReference> DefineAuditReferenceAsync() {
            return base.Channel.DefineAuditReferenceAsync();
        }
    }
}
